Interpolation of alpha cuts and change of default maximum alpha cut
cta-observatory/cta-lstchain pull request #1096
Opened 2023-05-12 12:02 UTC by SeiyaNozaki

Here I implemented the interpolation of `alpha` cuts as `gammaness` interpolation. In addition, I changed the default maximum alpha cut from 45 deg to 20 deg since it was too loose.

2023-05-12 16:48 UTC, chaimain commented on lstchain/high_level/tests/test_interpolate.py
> +                al_hdu_1 = fits.BinTableHDU(al_1, header=al_1_meta, name="GH_CUTS")
name as `AL_CUTS`

2023-05-12 20:44 UTC, chaimain approved these changes

2023-05-15 08:41 UTC, rlopezcoto commented
this PR is going to change the definition of the default ranges assumed when creating DL3 files, so it should also go into the next release and the target branch should be `ctapipe_v0.17` instead of `master`

2023-05-15 09:56 UTC, chaimain requested changes
@SeiyaNozaki Can you update the `interpolate_al_cuts` as per #1099 and we can rebase and then merge #1099 before this to have a good follow-up.

2023-05-18 17:31 UTC, chaimain commented on docs/examples/irf_tool_config.json
> +    "max_alpha_cut": 20,
These default values needs to be updated in `lstchain/io/event_selection` as well.

2023-05-23 13:04 UTC, chaimain approved these changes

2023-05-24 06:18 UTC, merged