Interpolation of RF predictions with cosZD, for homogeneous performance
cta-observatory/cta-lstchain pull request #1320
Opened 2024-11-27 09:55 UTC by moralejo

This should solve the issue of RF "performance jumps" at high zenith angles, when the pointing goes through the middle points between training nodes.
If the option is activated we call the RF predictors twice, for each of the two closest MC training nodes, then interpolate (or extrapolate) the values to the actual telescope pointing for each event.

Currently the training sample pointings are obtained from the path to the training sample(provided via command line). A better solution would be to add to the .sav files an array with the zenith and azimuth values of the MC training nodes.

2024-11-28 12:16 UTC, vuillaut commented
Hi @moralejo 
Thank you for making this implementation.
Early feedback: 
would it be possible to add the training and testing nodes of the current production as an ascii file in the lstchain data files to allow for testing without necessarily being on the cluster?
(astropy tables can be dumped to ascii easily) 
I completely agree these pointing nodes should be saved with the models during training and then loaded from there in the future.

2024-11-28 13:37 UTC, moralejo commented
> Hi @moralejo Thank you for making this implementation. Early feedback: would it be possible to add the training and testing nodes of the current production as an ascii file in the lstchain data files to allow for testing without necessarily being on the cluster? (astropy tables can be dumped to ascii easily)

Will do. What is better, just the zenith and azimuth values, or a list of the directory names?

2024-11-28 14:06 UTC, vuillaut commented
> > Hi @moralejo Thank you for making this implementation. Early feedback: would it be possible to add the training and testing nodes of the current production as an ascii file in the lstchain data files to allow for testing without necessarily being on the cluster? (astropy tables can be dumped to ascii easily)
> 
> Will do. What is better, just the zenith and azimuth values, or a list of the directory names?

I think the table of values that you can use directly at inference would be great (with appropriate metadata such as the date of export).

2024-11-28 14:19 UTC, moralejo commented
> > 
> > Will do. What is better, just the zenith and azimuth values, or a list of the directory names?
> 
> I think the table of values that you can use directly at inference would be great (with appropriate metadata such as the date of export).

Can you clarify exactly what metadata (and how? Just lines starting with # or whatever?)

2024-11-28 14:24 UTC, moralejo commented
What if we just write  in the config the two arrays of zeniths and azimuths?

2025-01-13 16:40 UTC, vuillaut requested changes
Hi Abelardo,
Sorry for the delay (and I still need to finish this later...).
I have made a couple of comments for improvement in the code/readability but overall the core logic looks good to me.

2025-01-13 16:40 UTC, vuillaut commented on lstchain/reco/dl1_to_dl2.py
> +    # Update the dataframe:
I don't see why converting to Series is necessary?

2025-01-13 16:40 UTC, vuillaut commented on lstchain/reco/dl1_to_dl2.py
> +                               alt1=pd.Series(second_closest_alt).values,
please use more explicit names for alt0, alt1, c0 and c1 in the dl2table that will end up being written

2025-01-13 16:40 UTC, vuillaut commented on lstchain/reco/dl1_to_dl2.py
> +    param_array.rename(columns={"alt_tel": "original_alt_tel"}, inplace=True)
I think it would be easier to change the features rather than this game of name-swapping:
```
 features_copy =  features.copy()  # avoid modifying features outside the function
 alt_index_in_features = features_copy.index('alt_tel')
 features_copy[alt_index_in_features] = 'alt0'
 predict_0 = rf.predict(param_array[features_copy])
 features_copy[alt_index_in_features] = 'alt1'
 predict_1 = ...
```
that's it

2025-01-13 16:40 UTC, vuillaut commented on lstchain/scripts/lstchain_dl1_to_dl2.py
> +        c3 = dir.find('_', c2)
```
# Regular expression to extract theta and az values
pattern = r"theta_(\d+\.\d+)_az_(\d+\.\d+)_"

# Search for matches
match = re.search(pattern, name)

if match:
    theta = float(match.group(1))  # First captured group is theta
    az = float(match.group(2))     # Second captured group is az
    print(f"Theta: {theta}, Az: {az}")
else:
    print("Pattern not found!")
```
would be more robust to find digital numbers

2025-01-13 16:40 UTC, vuillaut commented on lstchain/scripts/lstchain_dl1_to_dl2.py
> +        if 'interpolate_energy' in zdinter.keys():
slightly more readable:
```
interpolate_energy = zdinter.get('interpolate_energy', False)
```
and then you don't need to set it first, it is set to False here if `interpolate_energy` not in zdinter

2025-01-14 12:11 UTC, morcuended requested changes
Left some minor comments.

2025-01-14 12:11 UTC, morcuended commented on lstchain/scripts/lstchain_dl1_to_dl2.py
> +                                     dummy[dummy.rfind('/dec') + 1:]))
I think this should go to `lstchain.paths` module.

2025-01-14 12:11 UTC, morcuended commented on lstchain/scripts/lstchain_dl1_to_dl2.py
> +        if 'random_forest_zd_interpolation' in config.keys():
```suggestion
        if 'random_forest_zd_interpolation' in config:
```

2025-01-14 12:11 UTC, morcuended commented on lstchain/scripts/lstchain_dl1_to_dl2.py
> +        logger.warning('Cos(zenith) interpolation will be used in:')
log.info

2025-01-14 13:42 UTC, morcuended commented
> Can you clarify exactly what metadata (and how? Just lines starting with # or whatever?)

Regarding metadata, if you're using astropy Tables to later write ECSV files, you can define the metadata as:

```python
pointing_table = Table(...)
pointing_table.meta["export_date"] = datetime.today().strftime('%Y-%m-%d')
pointing_table.write("filepath_pointings.ecsv", format="ascii.ecsv")
```

2025-01-23 10:56 UTC, moralejo commented on lstchain/scripts/lstchain_dl1_to_dl2.py
> +        c3 = dir.find('_', c2)
This won't be needed with the ECVS file approach.

2025-01-23 11:08 UTC, moralejo commented
> 
> 1. the training directions are saved as ascii files, produced automatically with the models. At inference this ascii file is loaded with the model to get training direction. But we could actually produce these ascii files manually for the current productions and add them to the models directories in the cluster to allow for interpolated inference already.
> 
> To save the pointing directions as ascii files, I'd recommend starting from [astropy tables and save to `ecsv`](https://docs.astropy.org/en/latest/io/ascii/ecsv.html)

I have created the ECVS files for all directories of the new production, e.g.:
/fefs/aswg/data/models/AllSky/20240918_v0.10.12_allsky_nsb_tuning_0.00/dec_4822/training_dirs.ecsv
Please check if this is ok, I will change the code to use these.

2025-01-23 11:37 UTC, moralejo commented on lstchain/scripts/lstchain_dl1_to_dl2.py
> +                                     dummy[dummy.rfind('/dec') + 1:]))
No longer applies

2025-01-23 13:20 UTC, moralejo commented on lstchain/reco/dl1_to_dl2.py
> +    param_array.rename(columns={"alt_tel": "original_alt_tel"}, inplace=True)
Much better indeed

2025-01-23 14:58 UTC, moralejo commented on lstchain/reco/dl1_to_dl2.py
> +    param_array.rename(columns={"alt_tel": "original_alt_tel"}, inplace=True)
It seems that there is a check for the feature name, that is why I had gone for the column renaming (although I had forgotten by now)

2025-01-23 15:27 UTC, moralejo commented on lstchain/reco/dl1_to_dl2.py
> +    # Update the dataframe:
Can't recall now the exact error or warning, but I was forced to do this for it to work.

2025-01-23 15:35 UTC, moralejo commented on lstchain/reco/dl1_to_dl2.py
> +                               alt1=pd.Series(second_closest_alt).values,
I am not convinced, anything sufficiently descriptive to make looking into the code's comments unnecessary is probably too long  'alt_closest_mc_training_node'  'alt_second_closest_mc_training_node', then the same replacing but "alt" with "weight"...   The code itself becomes hard to read

2025-01-24 09:00 UTC, moralejo commented on lstchain/reco/dl1_to_dl2.py
> +    # Update the dataframe:
I removed the conversion and it still works, thanks!

2025-01-24 11:35 UTC, morcuended approved these changes
It looks good to me. I've just left some modifications on the docstrings following the numpydocs standard so it is later properly render in the documentation.

2025-01-24 11:42 UTC, morcuended approved these changes

2025-01-24 13:16 UTC, moralejo commented
Thanks @morcuended !
@vuillaut about the way to store and retrieve the training node pointings: is that ok? Can we merge?

2025-01-27 09:46 UTC, morcuended reviewed
I left one last comment.

> For this we would need to store also RFs trained with several pointings. Is that the case now?

No, right now dummy models are created from the test gamma MC, with single pointing

2025-01-27 14:31 UTC, moralejo commented on lstchain/reco/dl1_to_dl2.py
> +                                 'disp': False},
Done, thanks! I did not know about that problem, and it is indeed dangerous...

2025-01-27 14:32 UTC, moralejo commented
> I left one last comment.
> 
> > For this we would need to store also RFs trained with several pointings. Is that the case now?
> 
> No, right now dummy models are created from the test gamma MC, with single pointing

Ok, then we cannot introduce a unit test now. This is more than two months old, we need to move forward...

2025-01-27 14:59 UTC, morcuended approved these changes

2025-01-30 11:10 UTC, vuillaut approved these changes
Thank you for addressing my comments, I think it's good to go now !

2025-01-30 11:16 UTC, merged