Allow dla1b to take v0.9 dl1 files as input
cta-observatory/cta-lstchain pull request #1329
Opened 2024-12-19 15:48 UTC by moralejo

2025-01-07 11:27 UTC, morcuended requested changes

2025-01-07 11:27 UTC, morcuended commented on lstchain/scripts/lstchain_dl1ab.py
> +    except OSError:
Is `OSError` raised when trying to run with a v0.9 file without the try block?

2025-01-07 11:27 UTC, morcuended commented on lstchain/scripts/lstchain_dl1ab.py
> +        print("The standard LST optics and camera geometry will be used.")
use log.warning() instead of print

2025-01-09 15:18 UTC, moralejo commented on lstchain/scripts/lstchain_dl1ab.py
> +    except OSError:
Yes, I just used the same as in previous fixes of the same problem (in dl1 to dl2). This is what it yields:
OSError: Unsupported version of subarray table: 1.0

2025-01-09 15:24 UTC, morcuended commented
Looks good to me now (if it is ready for review)

2025-01-20 15:53 UTC, morcuended approved these changes
The exception type will be changed in ctapipe. Until then, it looks good as is.

2025-01-20 15:57 UTC, moralejo commented
> The exception type will be changed in ctapipe. Until then, it looks good as is.
Ok, thanks!

2025-01-20 15:57 UTC, merged