Add DL3+ notebooks
cta-observatory/cta-lstchain pull request #895
Opened 2022-01-28 10:57 UTC by chaimain

Adding 5 notebooks:
- MC DL2 to IRF (source-independent, fixed global and energy-dependent gammaness and theta cuts) 
- DL2 to DL3 (source-independent, fixed global and energy-dependent gammaness cuts)
- DL3 to DL4 (using gammapy v0.19 and saving DL4 as OGIP files)
- plot LC from DL4 (OGIP files)
- plot SED from DL4 (OGIP files)

The energy-dependent cuts procedures follows #709

2022-02-02 09:32 UTC, rlopezcoto commented
After v0.9 we should try to make all notebooks work with the current version of lstchain

2022-02-02 13:33 UTC, maxnoe requested changes
Why are there notebooks for things that are supposed to be done with the tools, e.g. `create_dl3_events_file` and `create_irfs`?

2022-02-02 13:33 UTC, maxnoe commented on lstchain/scripts/lstchain_merge_run_summaries.py
> +from pathlib import Path
This is a script from another PR and does not belong here

2022-02-02 13:39 UTC, chaimain commented
> Why are there notebooks for things that are supposed to be done with the tools, e.g. `create_dl3_events_file` and `create_irfs`?

To just show the workflow of the Tools.

2022-02-02 14:00 UTC, maxnoe commented
@chaimain But the notebooks duplicate code from the tools.

2022-02-02 14:07 UTC, chaimain commented
> @chaimain But the notebooks duplicate code from the tools.
Yes. I do not understand, how I can explain the workflow of the Tools, without doing so in a jupyter notebook. Can you elaborate more on this?

2022-02-02 14:10 UTC, maxnoe commented
@chaimain You show how you run the tools and explain what they do shortly in prose? Have a look in the inputs/outputs?

We really should not duplicate the code in notebooks that is supposed to be run via command line tools.

People who really want to understand the code need to look at the code, we shouldn't repeat it in a notebook

2022-02-02 14:12 UTC, chaimain commented
> @chaimain You show how you run the tools and explain what they do shortly in prose? Have a look in the inputs/outputs?
> 
> We really should not duplicate the code in notebooks that is supposed to be run via command line tools.
> 
> People who really want to understand the code need to look at the code, we shouldn't repeat it in a notebook


Ok. I understand it now. Thanks!
I will fix the notebooks accordingly.

2022-02-02 15:28 UTC, chaimain commented
@maxnoe should the `--help-all` section be run in the notebook?

2022-02-03 18:10 UTC, rlopezcoto commented
as commented at the beginning of the discussion, after the new release we should update all notebooks to make them work with the current version of lstchain and some of them like these ones should not contain the information that is better explained elsewhere (as in gammapy notebooks)

2022-02-03 18:10 UTC, rlopezcoto approved these changes

2022-02-03 18:11 UTC, merged