Some small improvements to DL3 Tools
cta-observatory/cta-lstchain pull request #943
Opened 2022-03-15 17:41 UTC by chaimain

Add a flag to not store DL3 as gzipped file and to be able to index DL3 files from nested directories.
Unzipped DL3 files can be used for faster analysis with gammapy, especially when dealing with large datasets or for source-dependent files.

2022-05-21 16:56 UTC, chaimain commented
To test the improvement in speed with unzipped DL3 files, I used files with a total of about 1E8 events, 30+ hrs of livetime of observations, and the spectral analysis worked in a few minutes, instead of about an hour.
Gammapy functions when trying to access information from each `Observation` object, tries to seek the specific DL3 files directly and takes some time to unzip a gzipped file every time.
@morcuended @SeiyaNozaki or others operating with such huge DL3 data, can you kindly confirm this improvement?

2022-05-25 18:32 UTC, morcuended commented
Thanks, @chaimain! I confirm the reduction in run time when using unzipped DL3 files in Gammapy. I would create the DL3 files unzipped by default instead of having a `--no-gzip` option.

2022-05-25 19:03 UTC, morcuended commented
Agreed with having the `--gzip` options instead.

2022-05-26 07:14 UTC, morcuended requested changes

2022-05-26 07:14 UTC, morcuended commented on lstchain/high_level/hdu_table.py
> +            file_list[0].absolute().resolve()
I'd say that `.absolute()` is not needed here. I think `.resolve()` already gives the absolute path.

2022-05-26 12:30 UTC, morcuended submitted a review, later dismissed

2022-05-26 13:52 UTC, morcuended approved these changes

2022-05-26 14:12 UTC, merged